# Generated by Django 5.2.5 on 2025-08-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='serverr',
            new_name='server',
        ),
    ]
